version: "3.8"

services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: mnemo_user
      POSTGRES_PASSWORD: mnemo_password
      POSTGRES_DB: mnemo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080" # Example port, adjust as needed
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://mnemo_user:mnemo_password@db:5432/mnemo_db?sslmode=disable

volumes:
  db_data:
