services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: mnemo_user
      POSTGRES_PASSWORD: mnemo_password
      POSTGRES_DB: mnemo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db_data:
