FROM golang:1.24-alpine

WORKDIR /app

# Install Air for hot-reloading
RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

# Command to run Air
CMD ["air"]
