name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci.yml"

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # Use a recent stable Go version compatible with 1.24

      - name: Build backend
        run: go build -v ./backend/...

      - name: Test backend
        run: go test -v ./backend/...

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a recent stable Node.js version

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build # Assuming a build script exists or will be added

      - name: Run frontend tests
        run: npm test # Assuming a test script exists or will be added
